eigerco/beerus

- beerus_cli/tests/cli.rs
- beerus_core/src/lightclient/beerus.rs
- beerus_core/src/lightclient/starknet/mod.rs
- beerus_core/tests/beerus.rs
- beerus_rest_api/tests/api.rs
The StarkNet block number is hardcoded
Issue Number: Fixes #34 
- Beerus fetches the last proven block on the fly through Helios
> feat(beerus_core): fetch last proven block on the fly

- .gitignore
- beerus_cli/src/ethereum/mod.rs
- beerus_cli/src/model.rs
- beerus_cli/src/runner.rs
- beerus_cli/tests/cli.rs
- beerus_cli/tests/model.rs
- beerus_core/src/lightclient/ethereum/helios_lightclient.rs
- beerus_core/src/lightclient/ethereum/mod.rs
- beerus_core/tests/beerus.rs
- beerus_rest_api/src/api/ethereum/endpoints.rs
- beerus_rest_api/src/api/ethereum/resp/mod.rs
- beerus_rest_api/src/lib.rs
- beerus_rest_api/tests/api.rs
Implemented the Ethereum RPC call `chain_id` + CLI + API + tests.
Note : the helios lightclient call `chain_id` returns a `u64` and cannot fail.
Issue Number: #78 
-
-
-
> Ethereum RPC `chain_id` query + CLI + API  + tests

- beerus_cli/src/main.rs
- beerusup
Reorder CLI arg parsing to come before environment variable configuration so we can expose usage flags like `--version` and `--help`.
Error on bad config when trying to print help
Issue Number: https://github.com/keep-starknet-strange/beerus/issues/82
- parse flags prior to config
Enables `beerusup` to use cli version instead of repo commit
> dev: reorder cli arg parsing

- beerus_core/src/lightclient/starknet/mod.rs
- beerus_core/src/lightclient/starknet/storage_proof.rs
- beerus_core/tests/data.json
- beerus_core/tests/proofs.rs
Adds the ability to verify a storage proof (as defined [here](https://github.com/eqlabs/pathfinder/issues/714)).
Closes #62 
Can't verify proofs
Issue Number: #62 
Can verify proofs
- Can verify contract proofs as well as storage proofs
- Added a `data.json` file for testing purposes (since RPC endpoint is not written yet, and pathfinder doesn't expose the endpoint either yet ([actually it does now](https://github.com/eqlabs/pathfinder/pull/787)).
- The `data.json` file was obtained by doing a curl on a modified version of pathfinder.
- `pathfinder` uses `starkhash` and here we use `FieldElement` so there's a bit of wrapping / translation going on.
- The verification is simply a method called on the `GetProofOutput` which should be easy …
> Add storage proof verification

- beerusup
Issue Number: Fix #116 
- `beerusup` uses `beerus_cli` full path on install
- No error and instead version is shown
> fix: beerusup uses beerus_cli full path on install

- Cargo.toml
Remove `cargo test --all` from pre-commit hooks via Husky 
the pre-commit hook generated by Husky will no longer generate lines for `cargo test --all`
- Husky would generate a pre-commit hook for `cargo test --all`
In order to stop testing all for each commit you will need to manually edit the `.git/hooks/pre-commit` file and remove the lines pertaining to testing.
> dev: remove precommit test all

- beerus_cli/src/model.rs
- beerus_cli/src/runner.rs
- beerus_cli/src/starknet/mod.rs
- beerus_cli/tests/cli.rs
- beerus_cli/tests/model.rs
- beerus_core/src/lightclient/beerus.rs
- beerus_core/src/lightclient/ethereum/mod.rs
- beerus_core/tests/beerus.rs
- beerus_rest_api/src/api/starknet/endpoints.rs
- beerus_rest_api/src/api/starknet/resp/mod.rs
- beerus_rest_api/src/lib.rs
- beerus_rest_api/tests/api.rs
Feature not implemented
Resolves #98 
Implemented in core, cli & api
I was not sure about the key of the response JSON in the API : used `result`, should it be `nonce` ?
> feat: l1ToL2MessageNonce

- beerus_cli/src/ethereum/mod.rs
- beerus_cli/src/model.rs
- beerus_cli/src/runner.rs
- beerus_cli/tests/cli.rs
- beerus_core/src/lightclient/ethereum/helios_lightclient.rs
- beerus_core/src/lightclient/ethereum/mod.rs
- beerus_core/tests/beerus.rs
- beerus_rest_api/src/api/ethereum/endpoints.rs
- beerus_rest_api/src/api/ethereum/resp/mod.rs
- beerus_rest_api/src/lib.rs
- beerus_rest_api/tests/api.rs
Implements the `eth_blockByNumber` RPC endpoint support
Issue Number: #84 
API endpoint `/ethereum/get_block_by_number/<block>/<full_tx>`, CLI command `query-block-by-number`, beerus core command implementation and tests for `eth_getBlockByNumber`
> feat: Ethereum RPC call "eth_blockByNumber"

- beerus_cli/src/model.rs
- beerus_cli/src/runner.rs
- beerus_cli/src/starknet/mod.rs
- beerus_cli/tests/cli.rs
- beerus_core/src/lightclient/starknet/mod.rs
- beerus_core/tests/beerus.rs
- beerus_rest_api/src/api/starknet/endpoints.rs
- beerus_rest_api/src/api/starknet/resp/mod.rs
- beerus_rest_api/src/lib.rs
- beerus_rest_api/tests/api.rs
* Added get_block_transaction_count CLI command.
* Added a new endpoint to fetch a number of transactions in a block 
* Implemented tests for Cli, Core and RestAPI
Issue Number: [#155 ](https://github.com/keep-starknet-strange/beerus/issues/155)
-
-
-
> feat: Starknet "get_block_transaction_count"

- Cargo.lock
- beerus_cli/src/model.rs
- beerus_cli/src/runner.rs
- beerus_cli/src/starknet/mod.rs
- beerus_cli/tests/cli.rs
- beerus_core/src/lightclient/starknet/mod.rs
- beerus_core/tests/beerus.rs
- beerus_rest_api/src/api/starknet/endpoints.rs
- beerus_rest_api/src/api/starknet/resp/mod.rs
- beerus_rest_api/src/lib.rs
- beerus_rest_api/tests/api.rs
- Added add_invoke_transaction CLI command.
- Added a new endpoint to add a invoke transaction on Starknet Network
Issue Number: #160
-
-
-
> feat: Starknet "add_invoke_transaction"

- beerus_cli/src/model.rs
- beerus_cli/src/runner.rs
- beerus_cli/src/starknet/mod.rs
- beerus_cli/tests/cli.rs
- beerus_core/src/lightclient/starknet/mod.rs
- beerus_core/tests/beerus.rs
- beerus_rest_api/src/api/starknet/endpoints.rs
- beerus_rest_api/src/api/starknet/resp/mod.rs
- beerus_rest_api/src/lib.rs
- beerus_rest_api/tests/api.rs
- Added get_transaction_by_block_id_and_index CLI command.
- Added a new endpoint to fetch a transaction given a block id and index on the Starknet Network
Issue Number: #151 
-
-
-
> feat: Starknet "get_transaction_by_block_id_and_index"

- Cargo.lock
- Cargo.toml
- README.md
- beerus_cli/Cargo.toml
- beerus_core/Cargo.toml
- beerus_rest_api/Cargo.toml
Moved workspace declarations including:
- name
- description
- husky dev dependencies
- [[bin]] 
Into the crates.
must change directory into a crate in order to run
ability to run --bin <binary_name> from the top level dir
> dev: workspace run top level binaries

- .github/workflows/check.yml
- .github/workflows/release.yml
- crates/beerus-cli/tests/cli.rs
dev: cache key for dependencies are not fork dependent
fresh dependency fetch/compile for each fork ci run
should use dependency cache across fork PRs
> dev: cache key for dependencies are not fork dependent

- .github/workflows/check.yml
- Cargo.lock
dont cache on failed run
cache on failed ci run
> dev: dont cache on failed run

- crates/beerus-rpc/src/api.rs
- crates/beerus-rpc/src/lib.rs
- examples/beerus-rpc/starknet_addDeployTransaction.hurl
Migrate `add_deploy_transaction` from `beerus-rest-api` to `beerus-rpc`.
Issue Number: #228 
- `add_deploy_transaction` has been moved to `beerus-rpc`.
- Add rpc example for `add_deploy_transaction`.
> feat: migrate Starknet: add_deploy_transaction to beerus-rpc

- crates/beerus-core/src/lightclient/beerus.rs
- crates/beerus-core/tests/beerus.rs
- crates/beerus-rpc/src/api.rs
- crates/beerus-rpc/src/lib.rs
Added query pending transactions to Beerus Lightclient and API
Light client cannot fetch pending transactions via [starknet_pendingTransactions](https://playground.open-rpc.org/?uiSchema%5BappBar%5D%5Bui:splitView%5D=false&schemaUrl=https://raw.githubusercontent.com/starkware-libs/starknet-specs/master/api/starknet_api_openrpc.json&uiSchema%5BappBar%5D%5Bui:input%5D=false&uiSchema%5BappBar%5D%5Bui:darkMode%5D=true&uiSchema%5BappBar%5D%5Bui:examplesDropdown%5D=false)
Issue Number: #231 
Pending Transactions can now be queried from starknet_pendingTransactions
tests included
> feat: Migrate Starknet : query_pending_transactions

- Cargo.lock
- Cargo.toml
- crates/beerus-core/src/lightclient/beerus.rs
When running `hurl` tests, `helios` panics and makes `beerus` crash.
Issue Number: #367 
The `hurl` tests pass, and all tests run with `cargo` are in green.
This was fixed recently by the new [release](https://github.com/a16z/helios/commit/1ae57f1b009efd33365d8fdbb61fde13354fa00b) of `helios` in branch `master` commit: `1ae57f1b009efd33365d8fdbb61fde13354fa00b`.
> bug: increment helios version to fix hurl tests

- crates/beerus-core/tests/config.rs
Tests are running in parallel by default, and we use 2 threads. Several tests are manipulating environment variables, which may cause conflicts if at least to of them run at the same time.
Sometimes tests are not passing in configuration, but we are not sure why.
Something we saw is that running the tests several time has different behavior (one time they fail,
other time they pass).
Adding the serial macro to a test that is modifying environment variable helps stabilizing
the runs. I have tested to run the tests with 2 / 4 / 8 / 10 threads, I can't make it fail
now.
-
-
-
> testing: ensure tests that modify env variable are run in serial

- Cargo.lock
- crates/beerus-core/Cargo.toml
- crates/beerus-core/src/config.rs
- crates/beerus-core/tests/config.rs
Tilde in environment variables are not expanded. For this reason, the default data dir `~/.beerus/tmp`
is created in the directory from where the command is executed.
Issue Number: #394 
The tilde is correctly expanded to fit the expected path.
-
-
-
> fix: expand of tilde from env variables value

- crates/beerus-rpc/src/lib.rs
- crates/beerus-rpc/src/utils.rs
`eth_` endpoints returning numbers are displayed in decimal. 
Issue Number: #422 
`eth_` endpoints returning numbers are now displayed as hexadecimal string.
This PR is not conflicted with #416 and can be merged to achieve some issues listed in #422.
> fix malformatted number to fit eth hex format (#422)

- crates/beerus-core/src/lightclient/ethereum/helios_lightclient.rs
- crates/beerus-rpc/src/main.rs
Removing existing feature: helios rpc server.
As discussed during the CC, as we are not doing
a proxy to helios, we then avoid having two
ports open at the same time when it's no longer required.
Helios RPC is no longer started, and only one port is used, the beerus port.
This will help the CI and dockerization PR #385.
> fix: remove helios rpc server

- crates/beerus-core/src/lightclient/beerus.rs
- crates/beerus-core/tests/beerus.rs
- crates/beerus-rpc/src/lib.rs
bug: Beerus stops processing incoming connections on hosts with less than 3 cpu
Beerus stops processing incoming connections on hosts with less than 3 cpu. Readers are created that starve the thread.
Issue Number: #438 
readers are capped to prevent deadlock when running on env with 2 cpu
> fix: Beerus stops processing incoming connections on hosts with less than 3 cpu

- README.md
- crates/beerus-core/examples/basic.rs
- crates/beerus-core/examples/call.rs
- crates/beerus-core/examples/client.rs
- crates/beerus-core/src/lightclient/beerus.rs
- crates/beerus-core/tests/beerus.rs
- crates/beerus-core/tests/integration.rs
- crates/beerus-js/src/lib.rs
- crates/beerus-rpc/src/main.rs
- crates/beerus-rpc/tests/common/mod.rs
Issue Number: #516
`BeerusLightClient::new` creates client from config only
Added function `BeerusLightClient::new_from_clients` which preserve old  `BeerusLightClient::new` behaviour for testing purpose
> Refactor: Init Beerus from config only

- crates/beerus-core/src/starknet_helper.rs
- crates/beerus-core/tests/beerus.rs
- crates/beerus-rpc/tests/common/mod.rs
Issue Number: #540 
The function `crates/beerus-rpc/src/starknet_helper.rs/block_id_string_to_block_id_type` is removed and tests are refactored to use starknet-rs block id type directly
N/A
> dev: remove block_id_string_to_block_id_type

- Cargo.lock
- crates/core/Cargo.toml
- crates/core/src/client.rs
Include a mermaid sequence diagram using aquamarine
Issue Number: loosely related to #550
> docs: Document the synchronization process

- Cargo.lock
- crates/core/Cargo.toml
- crates/core/src/block_hash/merkle_tree.rs
- crates/core/src/block_hash/mod.rs
- crates/core/src/lib.rs
Issue Number: Related to #550 
This implements block hashing as a preliminary step to #550. This was tested in `starknet-rs` but porting the test here will take more time and will be done in a separate PR.
This is one of the reasons why target branch of this PR is a feature branch.
The `starknet-rs` test can be previewed [here](https://github.com/xJonathanLEI/starknet-rs/compare/master...pierre-l:starknet-rs:block_hash#diff-1dcc3095e8fcdadf2919b5e85fe6c7122ae4b5d8c738153bee553cd8975af085)
> feat(550): Implement block hashing

- .github/workflows/ci.yml
- Cargo.lock
- Cargo.toml
- README.md
- crates/cli/Cargo.toml
- crates/core/Cargo.toml
- crates/rpc/Cargo.toml
- crates/rpc/src/api.rs
- crates/rpc/src/error.rs
- etc/conf/beerus.toml
Beerus is currently implicitly tied to the Starknet OpenRPC v0.5.1 spec. This PR upgrades the requirement to v0.6.0 and makes it more explicit in the README.md file. 
This is a breaking change. I bumped the Beerus version to v0.4.0 in this PR.
See #599 for more details about the motivation.
Commits will be squashed before merging.
> Bring support for the Starknet OpenRPC v0.6.0 spec

- crates/rpc/src/api.rs
- etc/rpc/mainnet/starknet_getEvents.hurl
Our `starknet_getEvents` signature differs from the spec.
The spec has a single "filter" parameter including the actual filter parameters as well as the paging parameters.
Our implementation separates both.
This PR brings our implementation closer to the spec.
[Method spec](https://github.com/starkware-libs/starknet-specs/blob/v0.6.0/api/starknet_api_openrpc.json#L768C9-L814C11):
```json
{
"name": "starknet_getEvents",
"summary": "Returns all events matching the given filter",
"description": "Returns all event objects matching the conditions in the provided filter",
"params": [
{
"name": "filter",
"summary": "The conditions used to filter the returned events",
"required": true,
"schema": {
"title": "Events request",
"allOf": [
{
"title": "Event filter",
"$ref": …
```
> fix: Make getEvents comply with the OpenRPC spec

- Cargo.lock
- crates/core/Cargo.toml
Helios 0.5.5 is required after Dencun update of the Ethereum mainnet.
Before (helios 0.5.4):
```
$ ./target/release/beerus -c tmp/beerus.toml
2024-03-13T21:46:40.537298Z  INFO beerus: init beerus client: MAINNET
2024-03-13T21:46:48.701516Z ERROR helios::consensus: sync failed err=invalid sync committee signature
```
After (helios 0.5.5):
```
$ ./target/release/beerus -c tmp/beerus.toml
2024-03-13T21:47:37.953161Z  INFO beerus: init beerus client: MAINNET
2024-03-13T21:47:44.324038Z  INFO helios::consensus: updated head               slot=8628535  confidence=98.63%  age=00:00:00:21
2024-03-13T21:47:44.947012Z  INFO helios::consensus: consensus client in sync with checkpoint: 0xede690aba0b6caf9213c2c32928d16baae51aa9644d76bfe65aa21f657663222
2024-03-13T21:47:50.599135Z  INFO beerus: Beerus …
```
> chore: bump helios to 0.5.5

- Cargo.lock
> chore: bump `mio` to 0.8.11

- Cargo.lock
- crates/core/Cargo.toml
- crates/core/src/client.rs
- crates/core/src/config.rs
This PR adds Sepolia testnet configuration instead of Goerli one.
Respective Seploia support is necessary from helios part as well:
https://github.com/a16z/helios/pull/326
> Add `SEPOLIA` network configuration

- README.md
- etc/conf/.env.example
This PR adds a RPC providers section to the README, which fixes [#602](https://github.com/eigerco/beerus/issues/602). I also reorganized it slightly, so I hope it is more readable now.
Also, since we introduced the `SEPOLIA` network here: https://github.com/eigerco/beerus/pull/612  there were still a few places that mentioned the deprecated `GORELI` network. I replaced all of them.
> Add RPC provider section to the README

- crates/core/src/client.rs
- crates/core/src/lib.rs
- crates/rpc/src/error.rs
Plain wrappers over `eyre::Report` do not make much sense at all
> chore: remove `CoreError` as redundant

- Cargo.lock
- Cargo.toml
https://github.com/eigerco/beerus/security/dependabot/26
> chore(deps): bump `eyre` to 0.6.12

- .github/workflows/hurl-integration-tests.yml
- .github/workflows/rust-integration-tests.yml
- Cargo.lock
- crates/core/src/config.rs
- crates/rpc/Cargo.toml
- crates/rpc/tests/rpc.rs
Re-implement the simplest Hurl-based test scenarios in rust
Create a new workflow for these tests: rust-integration-tests
Rename the old workflow to hurl-integration-tests
The new test suite only covers 11 scenarios out of 25 for now.
This new workflow still isn't as reliable as I'd want it to be. From what I can tell, Helios just fail to synchronize sometimes. It's nothing new. This will be my next area of focus.
> test: Chain-agnostic test suite

- .github/workflows/rust-integration-tests-alchemy.yml
- .github/workflows/rust-integration-tests-chainstack.yml
- .github/workflows/rust-integration-tests-reddio.yml
Run the ITs against Alchemy, Reddio and Chainstack.
Keep Alchemy as the default check for a git push.
Have the other two run periodically.
Bound the health check loop to a max timeout of 60s.
Increase the job timeout to 30 minutes. 15 minutes leaves too little room for the unexpected.
Although these all rely on Pathfinder, this may still help determine if any of these is more reliable than the others, and will offer us redundancy in the case of an incident on Alchemy's side. It's good for CI, but also for Beerus users.
Secrets & variables will have to be updated before merging this PR.
> ci: Run the ITs against multiple API providers

- crates/rpc/Cargo.toml
Some of these were marked as `dev-dependencies` while others were marked as optional in the main `dependencies` section.
[Related change](https://github.com/eigerco/beerus/pull/597/files#diff-ffd0a067e8dfc242560e9c699ab2ceb3b68c164e739f8840e527a9aec0f5106f)
Because these tests are hidden behind the `integration-tests` feature, all of these dependencies are currently optional.
Because `dev-dependencies` can't be marked as optional, I found it simpler to just move these to a subsection of the `dependencies` section.
> chore: Regroup the IT dependencies

- README.md
The CI badge is currently broken due to the recently renamed workflow files.
This change would make it point at the new alchemy workflow
Change preview:
> chore: Update the CI badge to the new workflow

- .github/workflows/rust-integration-tests-alchemy.yml
- .github/workflows/rust-integration-tests-chainstack.yml
- .github/workflows/rust-integration-tests-reddio.yml
- scripts/wait-for-it.sh
The previous health check still leaves the step in a successful state even if the timeout was reached. The workflow would then fail at the next step, with the tests failing to reach the Beerus server.
This new health check [properly fails in the case of a timeout](https://github.com/pierre-l/beerus-ci-test/actions/runs/8817006546/job/24202398593).
Because of the CI failure I noticed this morning, the timeout has been bumped from 60 seconds to 120.
> ci: Make the health check step fail in case of a timeout

- Cargo.lock
- crates/experimental-api/Cargo.toml
- crates/experimental-api/README.md
- crates/experimental-api/src/exe/err.rs
- crates/experimental-api/src/exe/map.rs
- crates/experimental-api/src/exe/mod.rs
- crates/experimental-api/src/gen.rs
- crates/experimental-api/src/rpc.rs
- crates/experimental-api/tests/common/mod.rs
- crates/experimental-api/tests/exe.rs
- crates/experimental-api/tests/rpc.rs
This PR completes stateless execution implementation (with necessary dependency upgrades) and exposes it through the RPC API (existing unit-test coverage is satisfied).
> feat: use stateless execution in the rpc api

- .github/workflows/check.yml
- Cargo.lock
- crates/core/examples/call.rs
- crates/experimental-api/tests/rpc.rs
- crates/rpc/Cargo.toml
- crates/rpc/tests/rpc.rs
This PR removes dysfunctional caching in the integration test suite and changes the test fixtures to a stream-based (potentially more async-friendly) implementation.
Most comfortable way to review is commit-by-commit.
> tests(rpc): clean up fixtures for integration tests

- .github/workflows/check.yml
- .github/workflows/hurl-integration-tests.yml
- .github/workflows/rust-integration-tests-alchemy.yml
- .github/workflows/rust-integration-tests-chainstack.yml
- .github/workflows/rust-integration-tests-reddio.yml
- Cargo.lock
- crates/experimental-api/src/exe/err.rs
- crates/experimental-api/tests/common/mod.rs
- crates/experimental-api/tests/exe.rs
- crates/experimental-api/tests/rpc.rs
- crates/rpc/Cargo.toml
- crates/rpc/tests/rpc.rs
This PR introduces macro fixtures (that allow less boilerplate code) and an env-variable that enforces running of the tests under `experimental-api` crate.
Going further, the env-var based approach allows making sure that tests are always compiled and always run according to the environment variables being set, which potentially gives better maintainability and flexibility compared to conditional compilation based test selection.
> chore(tests): organise fixtures

- .github/workflows/rust-integration-tests-alchemy.yml
- .github/workflows/rust-integration-tests-chainstack.yml
- .github/workflows/rust-integration-tests-reddio.yml
Fix for broken GitHub Actions workflows introduced in #647
> chore(ci): fix invalid workflow

- .github/dependabot.yml
This PR adds configuration to the repository so that Dependabot automatically updates the packages we use.
[Documentation](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates)
> chore(deps): enable dependabot

- Cargo.lock
- crates/cli/src/bin/beerus-experimental.rs
- crates/core/src/storage_proofs/mod.rs
- crates/core/src/storage_proofs/types.rs
- crates/core/src/utils.rs
- crates/experimental-api/Cargo.toml
- crates/experimental-api/src/gen.rs
- crates/experimental-api/src/lib.rs
- crates/experimental-api/src/proof_validation/mod.rs
- crates/experimental-api/src/rpc.rs
- crates/experimental-api/tests/common/mod.rs
- crates/experimental-api/tests/rpc.rs
Proof validation exists in `crates::core::storage_proofs`. Due to new requirements, it has been also implemented for the new experimental-api. Branch workflow is as follows:
- Creation of unit tests in the` crates::core::storage_proofs` to check the original implementation
- Migration of implementation to `crates::core::experimental_api::gen`
- Migration of unit tests to validate that it has the same functionality
- Code cleanup
Things to be checked with more details:
- Unit tests that have been created - does something need to be added or changed
- `jsonrpc::error` - code value for the errors is it correctly done (possible feature `impl From<FromStrError>` to kick out boilerplate `map_err()?` or different implementation with the current scope)
- usage of `starknet::FieldElemen`t due to …
> feat: proof validation implemented in experimental-api

- src/rpc.rs
- tests/common/mod.rs
- tests/rpc.rs
Updated check of requested block hash in `resolve_block_by_id` function
- Request of block by hash is checked by it's number representation
- Block root value is returned because of the proof validation
- Necessary changes in request of block by number
Unit tests for `resolve_block_by_id` function
- Test environment - Mock server for Starknet with custom response, state of Helios client
- User inputs of desired block and check with the response
Update of integration tests in `tests/rpc.rs`
- Additional requests by block hash and tag in `test_getStorageAt`
> feat: convert block hash to number

- Cargo.lock
- Cargo.toml
- README.md
- etc/conf/.env.example
- etc/conf/beerus.json
- etc/conf/beerus.toml
- examples/call.rs
- examples/state.rs
- src/bin/beerus.rs
- src/client.rs
- src/config.rs
- src/eth.rs
- web/beerus-web/Cargo.lock
- web/beerus-web/src/lib.rs
The main goal of this PR is to suggest rather radical change in configuration of Beerus: get rid of the `network` config property - it is completely redundant, because RPC URL for Ethereum and Starknet identify the used chain. In such case the detection of the network is very simple and allows no space for misconfiguration: only if both Etherem and Starknet chain IDs match (for either Ethereum or Sepolia), then network is detected correctly. In all other cases (unless 'testing' feature is enabled, then support of Katana chain was added explicitly) the error is returned. 
Other less significant suggestions:
- drop JSON configuration support and leave only TOML
- fail when invalid config properties were provided (now it falls back to the defaults for some reason)
- log updated state only if …
> feat!(config): drop `network` config property

- tests/rpc.rs
Closes https://github.com/eigerco/beerus/issues/711
> tests: cover latest block for `test_getStorageAt`

- tests/rpc.rs
Created two tests that interact with smart contracts on sepolia. Removed test_call because it uses same call on erc20 as an updated test. Updated test has couple of more calls:
- First interacts with erc20
- Second interacts with an existing account
> test: call existing contract

- Cargo.lock
- Cargo.toml
- src/eth.rs
- web/app.js
- web/beerus-web/Cargo.lock
- web/beerus-web/src/lib.rs
- web/run.sh
- web/wrk.js
This PR adds logging (into a browser's console when running Beerus through WebAssembly) of RPC calls latency, both to Ethereum via Helios and to Starknet. Any logging outside of wasm context is out of scope of this PR.
> perf(wasm): log RPC calls latency

- Cargo.lock
- Cargo.toml
- tests/account_katana.rs
- tests/starknet/contract/account/src/lib.cairo
- tests/starknet/mod.rs
- tests/starknet/scarb.rs
- tests/starknet/starkli.rs
- tests/starknet/utils.rs
With this PR, `starkli` library is introduced in test environment. Additionally, a test case has been created, that uses all of the major tools from `starknet` ecosystem:
- `scarb`
- `starkli`
- `katana`
- `beerus`
In the test case, a template account contract is compiled with `scarb`, manipulated with `starkli` and deployed via `beerus` to `katana`. Necessary updates were done on the template contract because of the deployment issue.
> test: deploy account on katana via beerus, scarb and starkli

- .github/workflows/account_deployment.yml
- .github/workflows/check.yml
- tests/account_katana.rs
- tests/common/ctx.rs
- tests/rpc.rs
- tests/starknet/starkli.rs
Created a test which deploys newly created accounts on sepolia. It has been scheduled that test is running on monthly basis.
> test: deploy new account to sepolia

- Cargo.lock
- Cargo.toml
- src/gen.rs
- tests/exe.rs
Closes https://github.com/eigerco/beerus/issues/861
> feat(gen): fix `Felt` to always match the regex
