eigerco/beerus

- cli/src/ethereum/mod.rs
- cli/src/lib.rs
- cli/src/model.rs
- cli/src/runner.rs
- core/src/config.rs
- core/src/lib.rs
- core/src/lightclient/beerus.rs
- core/src/lightclient/mod.rs
- core/src/lightclient/starknet/mod.rs
- src/lib.rs
> ♻️ refactor and init rust doc

- .github/workflows/test.yml
- beerus_core/tests/beerus.rs
> feat(ci): add ci in coverage

- .github/workflows/test.yml
- Cargo.lock
- beerus_cli/src/ethereum/mod.rs
- beerus_cli/src/starknet/mod.rs
- beerus_core/Cargo.toml
- beerus_core/src/config.rs
- beerus_core/src/lightclient/beerus.rs
- beerus_core/tests/beerus.rs
- beerus_core/tests/config.rs
- beerus_rest_api/src/main.rs
Issue Number: #38 
Test coverage has increased.
> Increase test coverage - Pass 1

- beerus_core/src/lightclient/beerus.rs
- beerus_core/src/lightclient/starknet/mod.rs
- beerus_core/tests/beerus.rs
- Beerus core can now call starknet_getStorageAt
> feat(beerus_core): add get_storage_at + tests

- .github/PULL_REQUEST_TEMPLATE.md
Pr template doesn't have the testing item
- PR template now has the testing item
> Fix pr template

- Cargo.lock
- beerus_rest_api/Cargo.toml
- beerus_rest_api/src/api/ethereum/endpoints.rs
- beerus_rest_api/src/api/ethereum/resp/mod.rs
- beerus_rest_api/src/api/mod.rs
- beerus_rest_api/src/api/starknet/endpoints.rs
- beerus_rest_api/src/api/starknet/resp/mod.rs
- beerus_rest_api/src/lib.rs
Issue Number: Fixes #43 
- openapi doc is exposed on `/openapi.json`
> Add doc endpoint

- Cargo.lock
- Cargo.toml
> feat(repo): add cargo husky

- beerus_cli/src/ethereum/mod.rs
- beerus_cli/src/model.rs
- beerus_cli/src/runner.rs
- beerus_cli/tests/cli.rs
- beerus_core/src/lightclient/ethereum/helios_lightclient.rs
- beerus_core/src/lightclient/ethereum/mod.rs
- beerus_core/tests/beerus.rs
- beerus_rest_api/src/api/ethereum/endpoints.rs
- beerus_rest_api/src/api/ethereum/resp/mod.rs
- beerus_rest_api/src/lib.rs
- beerus_rest_api/tests/api.rs
Implemented the Rpc call "query_nonce"
-
-
-
> Ethereum_RPC query_nonce + cli + cli_test implementation

- .gitignore
- beerus_cli/src/ethereum/mod.rs
- beerus_cli/src/main.rs
- beerus_cli/src/model.rs
- beerus_cli/src/runner.rs
- beerus_cli/tests/cli.rs
- beerus_core/src/lightclient/ethereum/helios_lightclient.rs
- beerus_core/src/lightclient/ethereum/mod.rs
- beerus_core/tests/beerus.rs
- beerus_rest_api/src/api/ethereum/endpoints.rs
- beerus_rest_api/src/api/ethereum/resp/mod.rs
- beerus_rest_api/src/lib.rs
- beerus_rest_api/tests/api.rs
Implemented the Rpc call "query_nonce"
Issue Number: #64 
- query block_number available through API and CLI
-
-
> CLI + API + core Ethereum RPC query block_number

- .all-contributorsrc
- README.md
> add contributors

- .markdownlint.json
- .prettierrc.json
- README.md
No linter for markdown file.
Use markdownlint file for defining Markdown rules.
Format README.md
I've added a `.prettierrc.json` as a lot of contributors use VSCode so that line length in markdown files is automatically adjusted.
> Markdown linting

- README.md
- beerusup
Implementation of Beerusup implementing similar install functionality as https://github.com/a16z/helios/blob/master/heliosup/install.
Issue Number: https://github.com/keep-starknet-strange/beerus/issues/6
Beerusup will pull the latest release bundle or build from source and place in local path for easy invocation.
-
-
-
The functionality of `install_beerus` is dependent on a release process that includes beerus builds for various platforms/architectures and those will be attached to the github release in a tarball.
> feature: beerusup

- .all-contributorsrc
- README.md
> Add contributor

- .github/CODEOWNERS
> Add Lucas code owner

- beerus_cli/src/model.rs
- beerus_cli/src/runner.rs
- beerus_cli/src/starknet/mod.rs
- beerus_cli/tests/cli.rs
- beerus_cli/tests/model.rs
- beerus_core/src/lightclient/starknet/mod.rs
- beerus_rest_api/src/api/starknet/endpoints.rs
- beerus_rest_api/src/api/starknet/resp/mod.rs
- beerus_rest_api/src/lib.rs
- beerus_rest_api/tests/api.rs
[Starknet RPC " chain_id" call](https://github.com/keep-starknet-strange/beerus/issues/87)
> :sparkles: Introducing starknet chain id

- .all-contributorsrc
- README.md
> add florian-bellotti

- Cargo.lock
- beerus_cli/src/main.rs
- beerus_core/src/config.rs
- beerus_core/src/lightclient/ethereum/helios_lightclient.rs
- beerus_core/tests/beerus.rs
- beerus_rest_api/src/main.rs
Check points now are fetch automatically when starting helioLightClient
-
-
-
> Automatic checkpoint fetching when starting HeliosLightClient

- beerus_cli/src/ethereum/mod.rs
- beerus_cli/src/model.rs
- beerus_cli/src/runner.rs
- beerus_cli/tests/cli.rs
- beerus_core/src/lightclient/ethereum/helios_lightclient.rs
- beerus_core/src/lightclient/ethereum/mod.rs
- beerus_core/tests/beerus.rs
- beerus_rest_api/src/api/ethereum/endpoints.rs
- beerus_rest_api/src/api/ethereum/resp/mod.rs
- beerus_rest_api/src/lib.rs
- beerus_rest_api/tests/api.rs
Implemented "query-code" RPC call.
Implemented:
-CLI Commands + tests
-Beerus Core implementation + tests
-RestAPI implementation + tests
-
-
-
> Reopened PR: Ethereum "Get_Code" RPC call (CLI, Core, RestAPI + tests)

- beerus_cli/src/model.rs
- beerus_cli/src/runner.rs
- beerus_cli/src/starknet/mod.rs
- beerus_cli/tests/cli.rs
- beerus_cli/tests/model.rs
- beerus_core/src/lightclient/starknet/mod.rs
- beerus_core/tests/beerus.rs
- beerus_rest_api/src/api/starknet/endpoints.rs
- beerus_rest_api/src/api/starknet/resp/mod.rs
- beerus_rest_api/src/lib.rs
- beerus_rest_api/tests/api.rs
Issue Number: Fix #88 
- add `block_number` API endpoint
- add `block_number` to core
- add `query_block_number` to CLI
> feat: add starknet rpc call block_number 

- beerus_cli/src/ethereum/mod.rs
- beerus_cli/src/model.rs
- beerus_cli/src/runner.rs
- beerus_cli/tests/cli.rs
- beerus_core/src/lightclient/ethereum/helios_lightclient.rs
- beerus_core/src/lightclient/ethereum/mod.rs
- beerus_core/tests/beerus.rs
- beerus_rest_api/src/api/ethereum/endpoints.rs
- beerus_rest_api/src/api/ethereum/resp/mod.rs
- beerus_rest_api/src/lib.rs
- beerus_rest_api/tests/api.rs
Implemented "query_block_transaction_count_by_number" RPC call.
Implemented:
-CLI Commands + tests
-Beerus Core implementation + tests
-RestAPI implementation + tests
Issue Number: #75
-
-
-
> feat: add ethereum "query_block_transaction_count_by_number" RPC call

- beerus_cli/src/model.rs
- beerus_cli/src/runner.rs
- beerus_cli/src/starknet/mod.rs
- beerus_cli/tests/cli.rs
- beerus_core/src/lightclient/beerus.rs
- beerus_core/tests/beerus.rs
- beerus_rest_api/src/api/starknet/endpoints.rs
- beerus_rest_api/src/api/starknet/resp/mod.rs
- beerus_rest_api/src/lib.rs
- beerus_rest_api/tests/api.rs
Implementation for the `l2-to-l1-messages` RPC call + tests
#101 
-
-
-
> feat: Starknet RPC l2-to-l1-messages

- README.md
Instruction in the readme on how to use the cli uses `beerus-cli`
Changed it to `beerus_cli`
> Fix a typo in the CLI section in the readme

- .all-contributorsrc
- README.md
> Add Tom giga chad

- Cargo.lock
- beerus_cli/Cargo.toml
- beerus_cli/src/model.rs
- beerus_cli/src/runner.rs
- beerus_cli/src/starknet/mod.rs
- beerus_cli/tests/cli.rs
- beerus_core/src/lib.rs
- beerus_core/src/lightclient/starknet/mod.rs
- beerus_core/src/starknet_helper.rs
- beerus_core/tests/beerus.rs
- beerus_rest_api/Cargo.toml
- beerus_rest_api/src/api/starknet/endpoints.rs
- beerus_rest_api/src/api/starknet/resp/mod.rs
- beerus_rest_api/src/lib.rs
- beerus_rest_api/tests/api.rs
Issue Number: Fix #90 
- add serde_json and base64 to dependencies
- add get_class to core
- add `starknet_helpers` file
- add get_class to CLI
- add get_class endpoint to API
> feat: add Starknet RPC `get_class` call

- beerus_cli/src/ethereum/mod.rs
- beerus_cli/src/model.rs
- beerus_cli/src/runner.rs
- beerus_cli/tests/cli.rs
- beerus_core/src/lightclient/ethereum/helios_lightclient.rs
- beerus_core/src/lightclient/ethereum/mod.rs
- beerus_core/tests/beerus.rs
- beerus_rest_api/src/api/ethereum/endpoints.rs
- beerus_rest_api/src/api/ethereum/resp/mod.rs
- beerus_rest_api/src/lib.rs
- beerus_rest_api/tests/api.rs
- Added query_get_price CLI command.
- Added a new endpoint to query gas price on the Ethereum Network. 
-
-
-
> feat: Ethereum "get_gas_price"

- Cargo.lock
- beerus_cli/Cargo.toml
- beerus_cli/src/ethereum/mod.rs
- beerus_cli/src/model.rs
- beerus_cli/src/runner.rs
- beerus_cli/tests/cli.rs
- beerus_core/src/lightclient/ethereum/helios_lightclient.rs
- beerus_core/src/lightclient/ethereum/mod.rs
- beerus_core/tests/beerus.rs
- beerus_rest_api/src/api/ethereum/endpoints.rs
- beerus_rest_api/src/api/ethereum/resp/mod.rs
- beerus_rest_api/src/lib.rs
- beerus_rest_api/tests/api.rs
Implements "estimate_gas" Ethereum RPC call
Issue Number: #77 
-
-
-
> feat: Ethereum estimate_gas RPC call

- beerus_cli/src/ethereum/mod.rs
- beerus_cli/src/model.rs
- beerus_cli/src/runner.rs
- beerus_cli/tests/cli.rs
- beerus_core/src/lightclient/ethereum/helios_lightclient.rs
- beerus_core/src/lightclient/ethereum/mod.rs
- beerus_core/tests/beerus.rs
- beerus_rest_api/src/api/ethereum/endpoints.rs
- beerus_rest_api/src/api/ethereum/resp/mod.rs
- beerus_rest_api/src/lib.rs
- beerus_rest_api/tests/api.rs
- Added send_raw_transaction CLI command.
- Added a new endpoint to send a raw transaction on Ethereum Network
-
-
-
> feat: Ethereum "send_raw_transaction"

- beerus_cli/src/model.rs
- beerus_cli/src/runner.rs
- beerus_cli/src/starknet/mod.rs
- beerus_cli/tests/cli.rs
- beerus_core/src/lightclient/starknet/mod.rs
- beerus_core/tests/beerus.rs
- beerus_rest_api/src/api/starknet/endpoints.rs
- beerus_rest_api/src/api/starknet/resp/mod.rs
- beerus_rest_api/src/lib.rs
- beerus_rest_api/tests/api.rs
- Added get_class_at CLI command.
- Added a new endpoint to fetch a smart contract class
Issue Number: #154 
-
-
-
> feat: Starknet "get_class_at"

- beerus_cli/src/ethereum/mod.rs
- beerus_cli/src/model.rs
- beerus_cli/src/runner.rs
- beerus_cli/tests/cli.rs
- beerus_core/src/lightclient/ethereum/helios_lightclient.rs
- beerus_core/src/lightclient/ethereum/mod.rs
- beerus_core/tests/beerus.rs
- beerus_rest_api/src/api/ethereum/endpoints.rs
- beerus_rest_api/src/api/ethereum/resp/mod.rs
- beerus_rest_api/src/lib.rs
- beerus_rest_api/tests/api.rs
There's no functionality to get logs.
Issue Number: [138](https://github.com/keep-starknet-strange/beerus/issues/138)
- Added functionality to berus_core for the RPC call "get_logs".
- Added CLI command.
- Added rest API endpoint.
> feat: Ethereum RPC call "get_logs"

- beerus_cli/src/model.rs
- beerus_cli/src/runner.rs
- beerus_cli/src/starknet/mod.rs
- beerus_cli/tests/cli.rs
- beerus_core/src/lightclient/starknet/mod.rs
- beerus_core/src/starknet_helper.rs
- beerus_core/tests/beerus.rs
- beerus_rest_api/src/api/starknet/endpoints.rs
- beerus_rest_api/src/api/starknet/resp/mod.rs
- beerus_rest_api/src/lib.rs
- beerus_rest_api/tests/api.rs
* Added syncing CLI command.
* Added a new endpoint to fetch an object about the sync status
* Implemented tests for Cli, Core and RestAPI
Issue Number: [#158 ](https://github.com/keep-starknet-strange/beerus/issues/158)
-
-
-
> feat: Starknet "syncing"

- beerus_cli/src/ethereum/mod.rs
- beerus_cli/src/model.rs
- beerus_cli/src/runner.rs
- beerus_cli/tests/cli.rs
- beerus_cli/tests/model.rs
- beerus_core/src/ethers_helper.rs
- beerus_core/src/lightclient/ethereum/helios_lightclient.rs
- beerus_core/src/lightclient/ethereum/mod.rs
- beerus_core/tests/beerus.rs
- beerus_rest_api/src/api/ethereum/endpoints.rs
- beerus_rest_api/src/api/ethereum/resp/mod.rs
- beerus_rest_api/src/lib.rs
- beerus_rest_api/tests/api.rs
Issue Number: fix #140 
- add eth get_transaction_count to core
- add eth query_transaction_count to CLI
- add eth tx_count to API
> feat: Ethereum "get_transaction_count"

- beerus_cli/src/model.rs
- beerus_cli/src/runner.rs
- beerus_cli/src/starknet/mod.rs
- beerus_cli/tests/cli.rs
- beerus_core/src/lightclient/starknet/mod.rs
- beerus_core/tests/beerus.rs
- beerus_rest_api/src/api/starknet/endpoints.rs
- beerus_rest_api/src/api/starknet/resp/mod.rs
- beerus_rest_api/src/lib.rs
- beerus_rest_api/tests/api.rs
* Added add_deploy_transaction_count CLI command.
* Added a new endpoint to add a deploy transaction on Starknet Network
* Implemented tests for Cli, Core and RestAPI
* Updated ethers library
Issue Number: [#162](https://github.com/keep-starknet-strange/beerus/issues/162)
-
-
-
> feat: Starknet RPC "add_deploy_transaction"

- beerus_cli/src/model.rs
- beerus_cli/src/runner.rs
- beerus_cli/src/starknet/mod.rs
- beerus_cli/tests/cli.rs
- beerus_core/src/lightclient/starknet/mod.rs
- beerus_core/tests/beerus.rs
- beerus_rest_api/src/api/starknet/endpoints.rs
- beerus_rest_api/src/api/starknet/resp/mod.rs
- beerus_rest_api/src/lib.rs
- beerus_rest_api/tests/api.rs
- Currently, there is no functionality for the RPC call "get_state_update"
Issue Number: #150 
- Added core functionality for said RPC call.
- Added related CLI command.
- Added related REST API endpoint.
> feat: RPC Starknet call  "get state update"

- beerus_cli/src/model.rs
- beerus_cli/src/runner.rs
- beerus_cli/src/starknet/mod.rs
- beerus_cli/tests/cli.rs
- beerus_core/src/lightclient/starknet/mod.rs
- beerus_core/tests/beerus.rs
- beerus_rest_api/src/api/starknet/endpoints.rs
- beerus_rest_api/src/api/starknet/resp/mod.rs
- beerus_rest_api/src/lib.rs
- beerus_rest_api/tests/api.rs
- Added pending_transactions CLI command.
- Added a new endpoint to fetch pending transactions on Starknet Network
Issue Number: #157
-
-
-
> feat: Starknet "pending_transactions" 

- Cargo.lock
- beerus_cli/src/main.rs
- beerus_cli/tests/cli.rs
- beerus_core/src/config.rs
- beerus_core/src/lightclient/beerus.rs
- beerus_core/src/lightclient/ethereum/helios_lightclient.rs
- beerus_core/tests/beerus.rs
- beerus_core/tests/config.rs
- beerus_core/tests/integration.rs
- beerus_rest_api/tests/api.rs
Update Beerus to use Beerus 0.2.0 which is wasmable.
-
-
-
> Feat: Migrate to helios 0.2.0

- beerus_cli/src/model.rs
- beerus_cli/src/runner.rs
- beerus_cli/src/starknet/mod.rs
- beerus_cli/tests/cli.rs
- beerus_core/src/lightclient/starknet/mod.rs
- beerus_core/tests/beerus.rs
- beerus_rest_api/src/api/starknet/endpoints.rs
- beerus_rest_api/src/api/starknet/resp/mod.rs
- beerus_rest_api/src/lib.rs
- beerus_rest_api/tests/api.rs
- No functionality to get a transaction by its hash.
Issue Number: #89 
- Added functionality to get a transaction by its hash.
- Added respective CLI commands and API endpoint.
> feat: Starknet RPC call  "get_transaction_by_hash"

- beerus_cli/src/model.rs
- beerus_cli/src/runner.rs
- beerus_cli/src/starknet/mod.rs
- beerus_cli/tests/cli.rs
- beerus_core/src/lightclient/starknet/mod.rs
- beerus_core/tests/beerus.rs
- beerus_rest_api/src/api/starknet/endpoints.rs
- beerus_rest_api/src/api/starknet/resp/mod.rs
- beerus_rest_api/src/lib.rs
- beerus_rest_api/tests/api.rs
- Nonexisting functionality for the get_tx_receipt starknet RPC call
Issue Number: #152
- Added functionality for the get_tx_receipt starknet RPC call.
- Added cli command and API endpoint.
> feat: Starknet RPC call "get_tx_receipt_call"

- beerus_cli/src/model.rs
- beerus_cli/src/runner.rs
- beerus_cli/src/starknet/mod.rs
- beerus_cli/tests/cli.rs
- beerus_core/src/lightclient/starknet/mod.rs
- beerus_core/tests/beerus.rs
- beerus_rest_api/src/api/starknet/endpoints.rs
- beerus_rest_api/src/api/starknet/resp/mod.rs
- beerus_rest_api/src/lib.rs
- beerus_rest_api/tests/api.rs
- Added add_declare_transaction CLI command.
- Added a new endpoint to add a declare transaction on Starknet Network
Issue Number: #161 
-
-
-
> feat: Starknet "add_declare_transaction"

- .github/workflows/release.yml
- beerusup
Update `beerusup` to install release binaries for the platform
feat
Install script only installs manually
Install script will pull latest released version from github
-
-
-
> beerusup to install release

- beerus_cli/src/model.rs
- beerus_cli/src/runner.rs
- beerus_cli/src/starknet/mod.rs
- beerus_cli/tests/cli.rs
- beerus_core/src/lightclient/beerus.rs
- beerus_core/src/lightclient/starknet/mod.rs
- beerus_core/src/starknet_helper.rs
- beerus_core/tests/beerus.rs
- beerus_rest_api/src/api/starknet/endpoints.rs
- beerus_rest_api/src/api/starknet/resp/mod.rs
- beerus_rest_api/src/lib.rs
- beerus_rest_api/tests/api.rs
Issue Number: Fix #156 
- add estimate_fee to core
- add estimate_fee to CLI
- add estimate_fee to API
> feat: add starknet RPC estimate_fee

- Cargo.lock
- beerus-rpc/Cargo.toml
- beerus-rpc/example_rpc_calls/stark_blockHashAndNumber.hurl
- beerus-rpc/src/beerus_rpc_server.rs
> feat: add block_hash_and_number RPC endpoint

- crates/beerus-rpc/example_rpc_calls/stark_blockHashAndNumber.hurl
- crates/beerus-rpc/example_rpc_calls/stark_blockNumber.hurl
- crates/beerus-rpc/example_rpc_calls/stark_blockWithTxHashes.hurl
- crates/beerus-rpc/example_rpc_calls/stark_chainId.hurl
- crates/beerus-rpc/example_rpc_calls/starknet_blockHashAndNumber.hurl
- crates/beerus-rpc/example_rpc_calls/starknet_blockNumber.hurl
- crates/beerus-rpc/example_rpc_calls/starknet_chainId.hurl
- crates/beerus-rpc/example_rpc_calls/starknet_getBlockTransactionCount.hurl
- crates/beerus-rpc/example_rpc_calls/starknet_getBlockWithTxHashes.hurl
- crates/beerus-rpc/src/beerus_rpc_server.rs
- Implement `stark_getBlockWithTxHashes`
- Rename `get_block_with_tx_hashes` to `stark_block_with_tx_hashes`
Issue Number: #232 
Fix #232
> feat: add stark_getBlockWithTxHashes RPC endpoint

- crates/beerus-rpc/example_rpc_calls/starknet_getClassAt.hurl
- crates/beerus-rpc/src/beerus_rpc_server.rs
- Implement `starknet_getClassAt` endpoint
Issue Number: #221 
Fix #221
> feat: add starknet_getClassAt RPC endpoint

- README.md
- examples/.env.example
- Update `.env.example` to correct `ETHEREUM_CONSENSUS_RPC_URL` format
- Update README
Issue Number: #254\
Fix #254
> docs: update .env.example and readme

- crates/beerus-rpc/example_rpc_calls/starknet_syncing.hurl
- crates/beerus-rpc/src/beerus_rpc_server.rs
* Implement `starknet_syncing` endpoint
* Add rpc example for `starknet_syncing` 
Issue Number: #225
> feat: add starknet_syncing RPC endpoint

- crates/beerus-rpc/example_rpc_calls/starknet_l1_to_l2_message_nonce.hurl
- crates/beerus-rpc/src/beerus_rpc_server.rs
* Implement `starknet_l1_to_l2_message_nonce` endpoint
* Add rpc example for `starknet_l1_to_l2_message_nonce`
Issue Number: #218
> feat: add starknet_l1_to_l2_message_nonce RPC endpoint

- crates/beerus-rpc/example_rpc_calls/starknet_l1_to_l2_message_cancellations.hurl
- crates/beerus-rpc/src/beerus_rpc_server.rs
* Implement `starknet_l1_to_l2_message_cancellations` endpoint
* Add rpc example for `starknet_l1_to_l2_message_cancellations`
Issue Number: #213
> feat: add starknet_l1_to_l2_message_cancellations RPC endpoints

- crates/beerus-rpc/example_rpc_calls/starknet_l1_to_l2_messages.hurl
- crates/beerus-rpc/src/beerus_rpc_server.rs
* Implement `starknet_l1_to_l2_messages` endpoint
* Add rpc example for `starknet_l1_to_l2_messages`
Issue Number: #214
> feat: add starknet_l1_to_l2_messages RPC endpoints

- crates/beerus-rpc/example_rpc_calls/l2_to_l1_messages.hurl
- crates/beerus-rpc/example_rpc_calls/starknet_l2_to_l1_messages.hurl
- crates/beerus-rpc/src/beerus_rpc_server.rs
> feat: Migrate Starknet : l2_to_l1_messages from "beerus_rest_api" to "beerus_rpc"

- .github/workflows/check.yml
- .github/workflows/release.yml
- crates/beerus-cli/tests/model.rs
rollback ci to the initial parallelized version
builds are slow in ci - dep caching broken
> dev: rollback ci

- crates/beerus-core/src/lightclient/beerus.rs
Implemented starknet `get_transaction_receipt`
Issue Number: #185 
- Adds `starknet_get_transaction_receipt` function
> feat: Add Verification Layer to "Starknet : get_transaction_receipt"

- crates/beerus-rpc/example_rpc_calls/starknet_getClassHash.hurl
- crates/beerus-rpc/src/server.rs
feat: Migrate Starknet : get_class_hash from "beerus_rest_api" to "beerus_rpc"
Issue Number: #220
> feat: Migrate Starknet : get_class_hash from "beerus_rest_api" to "beerus_rpc"

- crates/beerus-rpc/src/api.rs
- crates/beerus-rpc/src/lib.rs
- crates/beerus-rpc/tests/rpc.rs
- examples/beerus-rpc/ethereum_blockNumber.hurl
Addition of first ethereum endpoint: feat/ethereum_blockNumber
Ethereum endpoints are not implemented
Issue Number: #290 
The endpoint has been added + boilerplate to add other eth endpoints
Addition of test boilerplate for eth endpoints is needed to be able to test these new endpoints
> Addition of first ethereum endpoint: feat/ethereum_blockNumber

- crates/beerus-rpc/src/api.rs
- crates/beerus-rpc/src/lib.rs
- examples/beerus-rpc/starknet_getClass.hurl
Implement `starknet_getClass` endpoint
Issue Number: #219 
Fix #219
> feat: add starknet_getClass RPC endpoint

- Cargo.lock
- crates/beerus-rpc/Cargo.toml
- crates/beerus-rpc/src/api.rs
- crates/beerus-rpc/src/lib.rs
- crates/beerus-rpc/src/models.rs
- crates/beerus-rpc/tests/common/data/starknet_getEvents.json
- crates/beerus-rpc/tests/common/mod.rs
- crates/beerus-rpc/tests/rpc.rs
Issue Number: #224 
- Add `get_events` method to `BeerusRpc`
- Write unit test
> Feat: migrate starknet_getEvents to beerus-rpc

- crates/beerus-rpc/tests/common/data/starknet_syncing.json
- crates/beerus-rpc/tests/common/mod.rs
- crates/beerus-rpc/tests/rpc.rs
* Implemented test for RPC
Issue Number: #338 
-
-
-
> feat: add test starknet_syncing RPC

- crates/beerus-rpc/tests/common/data/starknet_getTransactionByBlockIdAndIndex.json
- crates/beerus-rpc/tests/common/mod.rs
- crates/beerus-rpc/tests/rpc.rs
* Implemented test for RPC
Issue Number: #340 
-
-
-
> feat: add test starknet_getTransactionByBlockIdAndIndex RPC

- crates/beerus-rpc/src/api.rs
- crates/beerus-rpc/src/lib.rs
- examples/beerus-rpc/starknet_addDeployAccountTransaction.hurl
- examples/beerus-rpc/starknet_getClassHashAt.hurl
get_class_hash -> get_class_hash_at (to match with Starknet documentation) addDeployTransaction -> addDeployAccountTransaction (to match with other projects of the ecosystem)
Fixed typos in method names: get_class_hash_at and add_deploy_transaction
Incorrect method name:
get_class_hash && add_deploy_transaction
correct names:
get_class_hash_at && add_deploy_account_transaction
> Fixed: typos in get_class_hash_at && add_deploy_account_transaction methods

- crates/beerus-rpc/src/api.rs
- crates/beerus-rpc/src/lib.rs
- examples/beerus-rpc/starknet_addInvokeTransaction.hurl
Implemented starknet_addInvokeTransaction
Not implemented
Issue Number: #324 
Given an invoke transaction returns an invokeTransactionResult
In collaboration with @bigherc18
> Implemented starknet_addInvokeTransaction

- Cargo.lock
- crates/beerus-rpc/Cargo.toml
- crates/beerus-rpc/src/lib.rs
Added correct formatting for hex encoding.
Issue Number: #427 
eth_getCode functions correctly, eth_call is still disfunctionning internaly.
> Added correct formating for eth_call & eth_getCode

- .github/workflows/check.yml
Add back in codecov bot to check and report on codebase test coverage for each PR
code coverage is not checked
Issue Number: #375 
Code coverage report is generated and uploaded to codecov.io
> feat: add back codecov bot

- .github/workflows/ci.yml
> added configurable ethereum_net + removed outdated comment

- .all-contributorsrc
- README.md
> :busts_in_silhouette: Add @phklive as a contributor

- README.md
Updated hurl visual representation after CI run with new functional and non-functional endpoints
Outdated representation
Issue Number: #426 
Updated representation
> Updated hurl visual representation after CI run

- .github/workflows/ci.yml
- Dockerfile
Beerus docker image is built from a ubuntu base image. 
Issue Number: #444 
This PR changes it to an alpine base, producing a final image 4 times lighter
> build: alpinize beerus docker image

- .github/workflows/check.yml
- .github/workflows/release.yml
build and publish docker container to `ghcr` during release
test action run [here](https://github.com/keep-starknet-strange/beerus/actions/runs/5073100833/jobs/9111680576)
no docker build/publish
Issue Number: #477 
build and publish docker container to `ghcr` during release
> feat: 477 docker publish

- crates/beerus-core/tests/beerus.rs
> test: added two test cases for get_storage_at

- README.md
> Fix StarkNet to Starknet

- crates/beerus-core/tests/common/mod.rs
- crates/beerus-core/tests/integration.rs
> Test/529 00 starknet/mod.rs

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/check.yml
- .github/workflows/ci.yml
- .github/workflows/mdbook.yml
> dev: trigger actions manually

- README.md
> dev: kss badge

- Cargo.lock
- crates/core/Cargo.toml
- crates/core/tests/config.rs
**Fixes the goerli_helios_json test**
> chore: Update Helios

- .github/workflows/check.yml
- crates/core/tests/block_hash.rs
Issue Number: Related to #550 
Tests #589
> test(550): Block hash verification

- CONTRIBUTING.md
Add a CONTRIBUTING.md file so we might avoid spending time on PRs that aren't compliant with our workflow.
> doc: Add a CONTRIBUTING.md file

- Cargo.lock
- crates/experimental-api/Cargo.toml
- crates/experimental-api/src/exe/err.rs
- crates/experimental-api/src/exe/map.rs
- crates/experimental-api/src/exe/mod.rs
- crates/experimental-api/src/gen.rs
- crates/experimental-api/src/rpc.rs
- crates/experimental-api/tests/common/mod.rs
- crates/experimental-api/tests/exe.rs
- crates/experimental-api/tests/rpc.rs
Implement missing pieces for stateless call execution and add simple test case for it.
> tests: stateless execution example

- crates/rpc/src/api.rs
- crates/rpc/src/error.rs
- crates/rpc/src/lib.rs
- etc/conf/beerus.json
- etc/conf/beerus.toml
Added check for spec version for beerus rpc client and remote starknet rpc client on rpc startup
> feat: RPC spec version check on startup

- crates/experimental-api/src/exe/err.rs
Closes https://github.com/eigerco/beerus/issues/636
> style: de-capitalize error messages

- Cargo.lock
- README.md
- crates/cli/src/bin/beerus-experimental.rs
- crates/cli/src/bin/beerus.rs
- crates/core/Cargo.toml
- crates/core/src/config.rs
Workflow summary
1. Introduced Validator crate that has trait Validate which can be used on Structs and it's attributes
2. Check for poll_secs
3. Check for URLs - Check whether the String is ok and perform a post on the url. If the returned http answer is ok, than the url is valid
4. Check for data dir - If the folder exists, check if is read only or not. If it doesn't exist, trace a warning.
5. Unit tests for behaviour validation
> feat(config): add validation

- tests/account.rs
- tests/common/constants.rs
- tests/common/matchers.rs
- tests/common/node.rs
Created starkli deploy workflow with the mock server
- Added additional test case
- Added new matchers for proper behaviour
- Added new constants
> test: deploy account test with mock server

- web/app.js
- web/index.html
- web/style.css
Add some CSS to make the page look user-friendly.
> feat(web/demo): make demo page look nice

- web/app.js
- web/etc/proxy/proxy.js
- web/index.html
- web/style.css
* Add a modal window with info
* Show the window on 'info' click
* Add proxy status indicator & button
> feat(web): add modal info window

- Cargo.toml
Closes https://github.com/eigerco/beerus/issues/809
> chore(bin): enable LTO for the release build

- .github/workflows/account_deployment.yml
Based on the error in actions:
`schedule accepts a list of one or more maps with the cron key set`
This should fix it and run test at 10 o'clock on each first of month
> bugfix: has to be a list cron type

- Cargo.lock
- Cargo.toml
- src/gen.rs
Puts together changes from https://github.com/eigerco/beerus/pull/848 https://github.com/eigerco/beerus/pull/849 https://github.com/eigerco/beerus/pull/850
> chore: bulk update dependencies
